<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKswfIdO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKswfIdO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKswfIdO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKswfIdO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKswfIdO\App_KernelDevDebugContainer([
    'container.build_hash' => 'KswfIdO',
    'container.build_id' => '2375a85f',
    'container.build_time' => 1603790053,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKswfIdO');
